{% set name = "gaspype" %}
{% set version = "1.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48e9b02d71ca93aec1b15cff40f837c339a2985889f6fcd8a9ba90326b08ee56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools >=64
    - setuptools-scm >=8
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >2.0.0

test:
  imports:
    - gaspype
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pandas # Required for running all tests
    - cantera # Required for running all tests
  source_files:
    - pyproject.toml
    - README.md
    - tests/*.py
  files:
    - tests/test_data/*.tsv
    - tests/test_data/*.csv
  commands:
    - pip check
    - rm tests/test_db_reader.py # Remove test that requires full repo
    - rm tests/test_doc_examples.py # Remove test that requires full repo
    - pytest

about:
  home: https://github.com/DLR-Institute-of-Future-Fuels/gaspype
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Performant library for thermodynamic calculations"

extra:
  recipe-maintainers:
    - Nonannet
