{% set name = "gaspype" %}
{% set version = "1.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74da86c34b6c71930c182c3177f3cf35bb93d5deae9175ba3a7c4c3f45645f1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0.1
    - numpy >2.0.0
    - scipy >1.12.0

test:
  imports:
    - gaspype
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pandas # Required for running all tests
    - cantera # Required for running all tests
  source_files:
    - pyproject.toml
    - README.md
    - tests/*.py
  files:
    - tests/test_data/*.tsv
    - tests/test_data/*.csv
  commands:
    - pip check
    - rm tests/test_db_reader.py # Remove test that requires full repo
    - rm tests/test_doc_examples.py # Remove test that requires full repo
    - pytest

about:
  home: https://github.com/DLR-Institute-of-Future-Fuels/gaspype
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Performant library for thermodynamic calculations"

extra:
  recipe-maintainers:
    - Nonannet
